[package]
name = "puffin-imgui"
version = "0.4.0"
authors = ["Embark <opensource@embark-studios.com>"]
description = "ImGui GUI bindings for the Puffin profiler"
license = "MIT OR Apache-2.0"
edition = "2018"
homepage = "https://github.com/EmbarkStudios/puffin"
repository = "https://github.com/EmbarkStudios/puffin"
readme = "README.md"
categories = ["development-tools::profiling", "gui"]
keywords = ["profiler", "instrumentation", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[lib]
doctest = false

[dependencies]
imgui = { version = "0.4" }
puffin = { version = "0.3.1", path = "../puffin" }
serde = { version = "1", features = ["derive"] }
